name: Deploy and Security Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        id: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

      - name: Get Deployment URL
        run: echo "::set-output name=url::$(cat $GITHUB_WORKSPACE/.deploy_url)"
        id: get_url

  dast:
    runs-on: ubuntu-latest
    needs: deploy  # Wait for deployment job to complete
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ steps.deploy.outputs.url }}  # Use the dynamically fetched URL from deploy job
